### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL: 

### ISSUE THREAD

**Issue by milkteanosugar** [veo-labs/cas-server-mock#6]
Hello, 

I received the following error when I tried to login to the page http://localhost:3004/:

TypeError [ERR_INVALID_URL]: Invalid URL: 
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at module.exports.authenticateAction (C:\Users\abc\Desktop\authentication\cas-server-mock\lib\controller.js:29:21)
    at Layer.handle [as handle_request] (C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\serve-static\index.js:121:7)
    at SendStream.emit (events.js:315:20)
    at SendStream.error (C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\send\index.js:270:17)
    at SendStream.onStatError (C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\send\index.js:421:12)
    at next (C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\send\index.js:735:16)
    at C:\Users\abc\Desktop\authentication\cas-server-mock\node_modules\send\index.js:743:23

The user.json file I created was like this:
[
  {
    "name": "001", 
    "attributes": { 
      "stringAttribute": "value",
      "arrayAttribute": "arrayValue"
    }
  }
]

I didn't config any other things. Could you please give me some instructions about how to solve this error? 

Thank you so much!

**Comment by maxime-beguin** [comment]
Hello!

CAS protocol expects a `service` parameter when accessing the authentication page which is the URL of the page to redirect when authenticated.
Try accessing the authentication page with `service` parameter. Something like: `http://localhost:3004/?service=http://localhost:3000/example`
